name: CI
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Laravel Helm Build - ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Setup PHP with PCOV
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, yaml
        coverage: pcov
    - name: Install Heml 3
      uses: azure/setup-helm@v4.0.0
      with:
        version: 'v3.12.2'
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.10.0
      with:
        minikube version: 'v1.32.0'
        kubernetes version: 'v1.29.0'
        github token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Kubernetes Proxy
      run: |
        kubectl proxy --port=8080 &

    - name: Install dependencies
      run: |
        composer install

    - name: Run tests
      run: |
        vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: kytoonlabs/laravel-helm
